# Taken from:
# https://github.com/crate-ci/typos/blob/master/docs/reference.md#example-configurations
default.extend-ignore-re = [
  # Disable spell-checking for an individual line.
  "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
  # Disable spell-checking for a code block.
  "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]
default.extend-identifiers = { "typ" = "typ" }
