//! Switch Logitech Easy-Switch devices to another host when the cursor is
//! pushed against an outer edge of the desktop.
//!
//! This library holds everything that does not touch the operating system, so
//! it can be tested without hardware. The binary adds the platform glue: the
//! real cursor and displays, and hidapi.

pub mod cli;
pub mod config;
pub mod desktop;
pub mod discover;
pub mod hid;
pub mod hidpp;
pub mod switch;
pub mod trigger;
pub mod watch;

/// The licenses of the third-party software compiled into edgehop, generated by
/// cargo-about.
pub const THIRD_PARTY_LICENSES: &str = include_str!("../THIRD_PARTY_LICENSES.txt");

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn includes_the_hidapi_c_library_license() {
        // cargo-about only finds the Rust crate's license on its own; see
        // about.toml.
        assert!(THIRD_PARTY_LICENSES.contains("Copyright (c) 2010, Alan Ott, Signal 11 Software"));
    }
}
